version: '3.3'
services:
        python-app:
                depends_on:
                        - "app_db"
                build:
                        context: ./python-app
                ports:
                        - "5000:5000"
                environment:
                        - test = testvalue
                        - DATABASE_PASSWORD=complexpassword
                        - DATABASE_HOST=db
                volumes:
                        - type: bind
                          source: ./python-app
                          target: /python-app
                networks:
                        - products
        app_db:
                image: mysql
                restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD=complexpassword
                        - MYSQL_DATABASE=Products
                ports:
                        - 8002:3306
                networks:
                        - products
networks:
        products:
