version: '3'
services:
        python-app:
                build:
                        context: ./python-app
                ports:
                        - "5000:5000"
                environment:
                        - test = testvalue
